import { PrismaClient, ScanStatus, Severity, IssueCategory, WorkspaceRole } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  const user = await prisma.user.upsert({
    where: { email: "maya@codeguardian.ai" },
    update: {},
    create: {
      email: "maya@codeguardian.ai",
      name: "Maya Chen",
      githubUsername: "maya-codeguardian",
    },
  });

  const team = await prisma.team.upsert({
    where: { slug: "guardian-workspace" },
    update: {},
    create: {
      name: "Guardian Workspace",
      slug: "guardian-workspace",
      plan: "PRO",
      members: {
        create: {
          userId: user.id,
          role: WorkspaceRole.ADMIN,
        },
      },
    },
  });

  const project = await prisma.project.upsert({
    where: { teamId_slug: { teamId: team.id, slug: "payments-api" } },
    update: {},
    create: {
      teamId: team.id,
      name: "Payments API",
      slug: "payments-api",
      language: "TypeScript",
      repoUrl: "https://github.com/acme/payments-api",
    },
  });

  const scan = await prisma.scan.create({
    data: {
      userId: user.id,
      projectId: project.id,
      status: ScanStatus.COMPLETED,
      language: "TypeScript",
      fileName: "api/auth/session.ts",
      codeHash: "seed-session-review",
      qualityScore: 88,
      complexity: "Medium",
      summary: "Seed review found a high-risk auth branch and missing negative-path tests.",
      completedAt: new Date(),
      issues: {
        create: [
          {
            title: "JWT expiry is not enforced before privileged action",
            severity: Severity.HIGH,
            category: IssueCategory.SECURITY,
            line: 42,
            explanation: "The handler trusts token shape but does not reject expired sessions before authorization.",
            fix: "Verify exp and issuer before checking role claims.",
            snippet: "if (session.role === 'admin') approve();",
          },
        ],
      },
      report: {
        create: {
          shareSlug: "seed-session-report",
          optimizedCode: "// Hardened session check generated by CodeGuardian AI",
          unitTests: "describe('session review', () => it('rejects expired tokens', () => {}));",
        },
      },
    },
  });

  await prisma.auditLog.create({
    data: {
      userId: user.id,
      teamId: team.id,
      action: "scan.completed",
      metadata: { scanId: scan.id, qualityScore: 88 },
    },
  });
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (error) => {
    console.error(error);
    await prisma.$disconnect();
    process.exit(1);
  });
