import { nanoid } from "nanoid";

import { generationPromptSchema, generatedSiteSchema, type GenerationPromptInput } from "@/features/ai/schema";
import { getOpenAI } from "@/services/openai";
import type { GeneratedSite, SiteSection } from "@/types/site";

function slugify(value: string) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)+/g, "")
    .slice(0, 42);
}

function inferMarket(prompt: string) {
  const lower = prompt.toLowerCase();
  if (lower.includes("portfolio")) return "creative portfolio";
  if (lower.includes("fintech")) return "fintech operating system";
  if (lower.includes("agency")) return "modern growth agency";
  if (lower.includes("crypto")) return "crypto intelligence platform";
  if (lower.includes("ecommerce")) return "commerce brand";
  if (lower.includes("developer")) return "developer tools company";
  return "AI SaaS platform";
}

export function buildFallbackSite(input: GenerationPromptInput): GeneratedSite {
  const market = inferMarket(input.prompt);
  const name = market
    .split(" ")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");

  const sections: SiteSection[] = [
    {
      id: nanoid(),
      type: "navbar",
      title: name,
      items: [
        { title: "Product", description: "#features" },
        { title: "Pricing", description: "#pricing" },
        { title: "Customers", description: "#testimonials" },
      ],
      cta: { label: "Start building", href: "#pricing" },
    },
    {
      id: nanoid(),
      type: "hero",
      eyebrow: "Generated by Nebula AI",
      title: `Launch a polished ${market} in minutes`,
      subtitle:
        "Nebula turns strategy, copy, layout, and responsive production UI into a live website you can edit, export, and publish.",
      body: input.prompt,
      cta: { label: "Generate your site", href: "/dashboard/generate" },
    },
    {
      id: nanoid(),
      type: "bento",
      eyebrow: "AI-native workflow",
      title: "Every block is generated as structured, editable product DNA.",
      subtitle: "No screenshots. No locked templates. Real sections, real content, real exportable code.",
      items: [
        { title: "Prompt to layout", description: "Generate full IA, sections, responsive grid decisions, and launch copy from a single brief." },
        { title: "Brand system", description: "Create palettes, typography, gradients, and reusable styles that stay consistent across pages." },
        { title: "Editor ready", description: "Every section is reorderable, versioned, commentable, and ready for inline edits." },
        { title: "Publish pipeline", description: "Ship to Nebula subdomains, connect custom domains, and export a Next.js codebase." },
      ],
    },
    {
      id: nanoid(),
      type: "features",
      eyebrow: "Capabilities",
      title: "The website builder for teams that need taste and velocity.",
      items: [
        { title: "AI generation engine", description: "Structured JSON schemas create layouts, copy, SEO, and component variants with guardrails." },
        { title: "Visual editing", description: "Drag sections, edit text inline, tune color and type, switch responsive preview, and autosave." },
        { title: "Collaboration", description: "Comments, activity, workspace roles, and version history keep teams moving together." },
        { title: "Revenue ready", description: "Stripe subscriptions, usage limits, credits, and plan gates are wired into the app architecture." },
      ],
    },
    {
      id: nanoid(),
      type: "stats",
      title: "Built for ambitious product teams",
      items: [
        { title: "94%", description: "Less time from brief to first publishable version" },
        { title: "12k", description: "AI credits included on team workspaces" },
        { title: "1-click", description: "Publishing, sitemap, OpenGraph, and export workflows" },
      ],
    },
    {
      id: nanoid(),
      type: "pricing",
      eyebrow: "Pricing",
      title: "Start free, scale when the websites start shipping.",
      items: [
        { title: "Free", meta: "$0", description: "3 projects, 100 AI credits, Nebula subdomain." },
        { title: "Pro", meta: "$29", description: "Unlimited projects, custom domains, export, 2,500 credits." },
        { title: "Team", meta: "$99", description: "Roles, comments, version history, 12,000 credits." },
      ],
    },
    {
      id: nanoid(),
      type: "testimonials",
      eyebrow: "Customer signal",
      title: "Teams use Nebula when the website needs to feel inevitable.",
      items: [
        { title: "Maya Chen, Founder", description: "Nebula gave us a launch page that looked like our Series A happened early." },
        { title: "Jon Bell, Studio Lead", description: "The structured output means our designers can refine instead of starting from a blank canvas." },
        { title: "Avery Singh, Growth", description: "We ship campaign pages in an afternoon and keep every variant on brand." },
      ],
    },
    {
      id: nanoid(),
      type: "faq",
      title: "Questions before launch",
      items: [
        { title: "Can I export code?", description: "Yes. Nebula packages generated sections into a Next.js-ready export." },
        { title: "Can I publish with a custom domain?", description: "Yes. Projects support Nebula subdomains, SEO metadata, sitemaps, and custom-domain fields." },
        { title: "Does it support teams?", description: "Yes. Workspaces include roles, comments, activity logs, and version history." },
      ],
    },
    {
      id: nanoid(),
      type: "cta",
      title: "Create the website your next customer expects.",
      subtitle: "Prompt Nebula, refine visually, publish confidently.",
      cta: { label: "Open the generator", href: "/dashboard/generate" },
    },
    {
      id: nanoid(),
      type: "footer",
      title: name,
      subtitle: "Generated, edited, published, and exported with Nebula AI.",
    },
  ];

  return {
    name,
    slug: `${slugify(name)}-${nanoid(5)}`,
    prompt: input.prompt,
    palette: {
      background: "#05070f",
      foreground: "#f8fafc",
      primary: "#8b5cf6",
      accent: "#22d3ee",
    },
    typography: {
      heading: "Space Grotesk",
      body: "Inter",
    },
    seo: {
      title: `${name} | Built with Nebula AI`,
      description: `A premium ${market} website generated from: ${input.prompt}`,
    },
    sections,
  };
}

export async function generateWebsite(input: unknown) {
  const parsed = generationPromptSchema.parse(input);

  if (!process.env.OPENAI_API_KEY) {
    return buildFallbackSite(parsed);
  }

  const openai = getOpenAI();
  const completion = await openai.chat.completions.create({
    model: process.env.OPENAI_MODEL || "gpt-4.1-mini",
    temperature: 0.65,
    response_format: { type: "json_object" },
    messages: [
      {
        role: "system",
        content:
          "Generate production website JSON for Nebula AI. Return only valid JSON with name, slug, prompt, palette, typography, seo, sections. Sections must use types navbar, hero, bento, features, stats, pricing, testimonials, faq, cta, footer.",
      },
      {
        role: "user",
        content: JSON.stringify(parsed),
      },
    ],
  });

  const raw = completion.choices[0]?.message.content;
  if (!raw) return buildFallbackSite(parsed);

  const json = JSON.parse(raw);
  return generatedSiteSchema.parse({
    ...json,
    prompt: parsed.prompt,
  });
}
